export default [
    "'Ready for love'",
    "'Most dramatic season ever'",
    "'I've never felt this way'",
    "Mentions Tia",
    "Mentions Becca",
    "'I didn't think it would be this hard'",
    "'Best friend'",
    "'Real world'",
    "'The one'",
    "'Spend the rest of my life'",
    "Virginity",
    "'Trust the process'",
    "Shirtless Colton",
    "'Right reasons'",
    "Makeout session",
    "'I can see myself...'",
    "'Not here to make friends'",
    "'Have a connection'",
    "Tells Colton what someone else said/did",
    "Fireworks",
    "Concert",
    "Colton staring off into the distance",
    "'Falling for Colton'",
    "'Former NFL player'",
    "'Man/woman of my dreams'",
    "'Next chapter'",
    "Colton talks about his family",
    "'Life changing'"
];